{
    "3DS Acessórios": {
        "id": 101,
        "fatherId": 1,
        "title": "3DS Acessórios",
        "url": "https://pt.webuy.com/search?categoryIds=975&categoryName=3DS%20Acess%C3%B3rios",
        "image": "https://pt.static.webuy.com/images/category/3ds-acess%C3%B3rios.jpg",
        "hub_consola": True,
        "hub_acessorios": True,
        "hub_jogos": False,
    },
    "3DS Consolas": {
        "id": 102,
        "fatherId": 1,
        "title": "3DS Consolas",
        "url": "https://pt.webuy.com/search?categoryIds=976&categoryName=3DS%20Consolas",
        "image": "https://pt.static.webuy.com/images/category/3ds-consolas.jpg",
        "hub_consola": False,
        "hub_acessorios": False,
        "hub_jogos": False,
    },
    "3DS Jogos": {
        "id": 103,
        "fatherId": 1,
        "title": "3DS Jogos",
        "url": "https://pt.webuy.com/search?categoryIds=1008&categoryName=3DS%20Jogos",
        "image": "https://pt.static.webuy.com/images/category/3ds-jogos.jpg",
        "hub_consola": False,
        "hub_acessorios": False,
        "hub_jogos": True,
    },
    "DS Acessórios": {
        "id": 201,
        "fatherId": 2,
        "title": "DS Acessórios",
        "url": "https://pt.webuy.com/search?categoryIds=835&categoryName=DS%20Acess%C3%B3rios",
        "image": "https://pt.static.webuy.com/images/category/ds-acess%C3%B3rios.jpg",
        "hub_consola": True,
        "hub_acessorios": True,
        "hub_jogos": False,
    },
    "DS Consolas": {
        "id": 202,
        "fatherId": 2,
        "title": "DS Consolas",
        "url": "https://pt.webuy.com/search?categoryIds=836&categoryName=DS%20Consolas",
        "image": "https://pt.static.webuy.com/images/category/ds-consolas.jpg",
        "hub_consola": False,
        "hub_acessorios": False,
        "hub_jogos": False,
    },
    "DS Jogos": {
        "id": 203,
        "fatherId": 2,
        "title": "DS Jogos",
        "url": "https://pt.webuy.com/search?categoryIds=769&categoryName=DS%20Jogos",
        "image": "https://pt.static.webuy.com/images/category/ds-jogos.jpg",
        "hub_consola": False,
        "hub_acessorios": False,
        "hub_jogos": True,
    },
    "GameCube Acessórios": {
        "id": 301,
        "fatherId": 3,
        "title": "GameCube Acessórios",
        "url": "https://pt.webuy.com/search?categoryIds=839&categoryName=GameCube%20Acess%C3%B3rios",
        "image": "https://pt.static.webuy.com/images/category/gamecube-acess%C3%B3rios.jpg",
        "hub_consola": True,
        "hub_acessorios": True,
        "hub_jogos": False,
    },
    "Gamecube Consolas": {
        "id": 302,
        "fatherId": 3,
        "title": "Gamecube Consolas",
        "url": "https://pt.webuy.com/search?categoryIds=838&categoryName=GameCube%20Consolas",
        "image": "https://pt.static.webuy.com/images/category/gamecube-consolas.jpg",
        "hub_consola": False,
        "hub_acessorios": False,
        "hub_jogos": False,
    },
    "GameCube Jogos": {
        "id": 303,
        "fatherId": 3,
        "title": "GameCube Jogos",
        "url": "https://pt.webuy.com/search?categoryIds=667&categoryName=GameCube%20Jogos",
        "image": "https://pt.static.webuy.com/images/category/gamecube-jogos.jpg",
        "hub_consola": False,
        "hub_acessorios": False,
        "hub_jogos": True,
    },
    "Figuras NFC": {
        "id": 401,
        "fatherId": 4,
        "title": "Figuras NFC",
        "url": "https://pt.webuy.com/search?categoryIds=1003&categoryName=Figuras%20NFC",
        "image": "https://pt.static.webuy.com/images/category/figuras-nfc.jpg",
        "hub_consola": True,
        "hub_acessorios": False,
        "hub_jogos": False,
    },
    "Playstation2 Acessórios": {
        "id": 402,
        "fatherId": 4,
        "title": "Playstation2 Acessórios",
        "url": "https://pt.webuy.com/search?categoryIds=404&categoryName=Playstation2%20Acess%C3%B3rios",
        "image": "https://pt.static.webuy.com/images/category/playstation2-acess%C3%B3rios.jpg",
        "hub_consola": True,
        "hub_acessorios": True,
        "hub_jogos": False,
    },
    "Playstation3Acessórios": {
        "id": 403,
        "fatherId": 4,
        "title": "Playstation3Acessórios",
        "url": "https://pt.webuy.com/search?categoryIds=823&categoryName=Playstation3%20Acess%C3%B3rios",
        "image": "https://pt.static.webuy.com/images/category/playstation3-acess%C3%B3rios.jpg",
        "hub_consola": True,
        "hub_acessorios": True,
        "hub_jogos": False,
    },
    "Playstation4 Acessórios": {
        "id": 404,
        "fatherId": 4,
        "title": "Playstation4 Acessórios",
        "url": "https://pt.webuy.com/search?categoryIds=1015&categoryName=Playstation4%20Acessorios",
        "image": "https://pt.static.webuy.com/images/category/playstation4-acessorios.jpg",
        "hub_consola": True,
        "hub_acessorios": True,
        "hub_jogos": False,
    },
    "Playstation5 Acessorios": {
        "id": 405,
        "fatherId": 4,
        "title": "Playstation5 Acessorios",
        "url": "https://pt.webuy.com/search?categoryIds=1087&categoryName=Playstation5%20Acessorios",
        "image": "https://pt.static.webuy.com/images/category/playstation5-acessorios.jpg",
        "hub_consola": True,
        "hub_acessorios": False,
        "hub_jogos": False,
    },
    "PS Vita Acessórios": {
        "id": 406,
        "fatherId": 4,
        "title": "PS Vita Acessórios",
        "url": "https://pt.webuy.com/search?categoryIds=989&categoryName=PS%20Vita%20Acess%C3%B3rios",
        "image": "https://pt.static.webuy.com/images/category/ps-vita-acess%C3%B3rios.jpg",
        "hub_consola": True,
        "hub_acessorios": True,
        "hub_jogos": False,
    },
    "PSP Acessórios": {
        "id": 407,
        "fatherId": 4,
        "title": "PSP Acessórios",
        "url": "https://pt.webuy.com/search?categoryIds=864&categoryName=PSP%20Acess%C3%B3rios",
        "image": "https://pt.static.webuy.com/images/category/psp-acess%C3%B3rios.jpg",
        "hub_consola": True,
        "hub_acessorios": True,
        "hub_jogos": False,
    },
    "Switch Acessorios": {
        "id": 408,
        "fatherId": 4,
        "title": "Switch Acessorios",
        "url": "https://pt.webuy.com/search?categoryIds=1047&categoryName=Switch%20Acessorios",
        "image": "https://pt.static.webuy.com/images/category/switch-acessorios.jpg",
        "hub_consola": True,
        "hub_acessorios": False,
        "hub_jogos": False,
    },
    "Wii Acessórios": {
        "id": 409,
        "fatherId": 4,
        "title": "Wii Acessórios",
        "url": "https://pt.webuy.com/search?categoryIds=1013&categoryName=Wii%20Acessorios",
        "image": "https://pt.static.webuy.com/images/category/wii-acessorios.jpg",
        "hub_consola": True,
        "hub_acessorios": True,
        "hub_jogos": False,
    },
    "Wii-U Acessórios": {
        "id": 4010,
        "fatherId": 4,
        "title": "Wii-U Acessórios",
        "url": "https://pt.webuy.com/search?categoryIds=1014&categoryName=Wii-U%20Acessorios",
        "image": "https://pt.static.webuy.com/images/category/wii-u-acessorios.jpg",
        "hub_consola": True,
        "hub_acessorios": True,
        "hub_jogos": False,
    },
    "Xbox 360Acessórios": {
        "id": 4011,
        "fatherId": 4,
        "title": "Xbox 360Acessórios",
        "url": "https://pt.webuy.com/search?categoryIds=768&categoryName=Xbox%20360%20Acess%C3%B3rios",
        "image": "https://pt.static.webuy.com/images/category/xbox-360-acess%C3%B3rios.jpg",
        "hub_consola": True,
        "hub_acessorios": True,
        "hub_jogos": False,
    },
    "Xbox Acessórios": {
        "id": 4012,
        "fatherId": 4,
        "title": "Xbox Acessórios",
        "url": "https://pt.webuy.com/search?categoryIds=671&categoryName=Xbox%20Acess%C3%B3rios",
        "image": "https://pt.static.webuy.com/images/category/xbox-acess%C3%B3rios.jpg",
        "hub_consola": True,
        "hub_acessorios": True,
        "hub_jogos": False,
    },
    "Xbox One Acessórios": {
        "id": 4013,
        "fatherId": 4,
        "title": "Xbox One Acessórios",
        "url": "https://pt.webuy.com/search?categoryIds=1016&categoryName=Xbox%20One%20Acessorios",
        "image": "https://pt.static.webuy.com/images/category/xbox-one-acessorios.jpg",
        "hub_consola": True,
        "hub_acessorios": True,
        "hub_jogos": False,
    },
    "Xbox Series Acessorios": {
        "id": 4014,
        "fatherId": 4,
        "title": "Xbox Series Acessorios",
        "url": "https://pt.webuy.com/search?categoryIds=1090&categoryName=Xbox%20Series%20Acessorios",
        "image": "https://pt.static.webuy.com/images/category/xbox-series-acessorios.jpg",
        "hub_consola": True,
        "hub_acessorios": False,
        "hub_jogos": False,
    },
    "MicroConsolas": {
        "id": 501,
        "fatherId": 5,
        "title": "MicroConsolas",
        "url": "https://pt.webuy.com/search?categoryIds=1045&categoryName=MicroConsolas",
        "image": "https://pt.static.webuy.com/images/category/microconsolas.jpg",
        "hub_consola": False,
        "hub_acessorios": False,
        "hub_jogos": False,
    },
    "Playstation2 Consolas": {
        "id": 502,
        "fatherId": 5,
        "title": "Playstation2 Consolas",
        "url": "https://pt.webuy.com/search?categoryIds=402&categoryName=Playstation2%20Consolas",
        "image": "https://pt.static.webuy.com/images/category/playstation2-consolas.jpg",
        "hub_consola": False,
        "hub_acessorios": False,
        "hub_jogos": False,
    },
    "Playstation3 Consolas": {
        "id": 503,
        "fatherId": 5,
        "title": "Playstation3 Consolas",
        "url": "https://pt.webuy.com/search?categoryIds=822&categoryName=Playstation3%20Consolas",
        "image": "https://pt.static.webuy.com/images/category/playstation3-consolas.jpg",
        "hub_consola": False,
        "hub_acessorios": False,
        "hub_jogos": False,
    },
    "Playstation4 Consolas": {
        "id": 504,
        "fatherId": 5,
        "title": "Playstation4 Consolas",
        "url": "https://pt.webuy.com/search?categoryIds=999&categoryName=Playstation4%20Consolas",
        "image": "https://pt.static.webuy.com/images/category/playstation4-consolas.jpg",
        "hub_consola": False,
        "hub_acessorios": False,
        "hub_jogos": False,
    },
    "Playstation5 Consolas": {
        "id": 505,
        "fatherId": 5,
        "title": "Playstation5 Consolas",
        "url": "https://pt.webuy.com/search?categoryIds=1088&categoryName=Playstation5%20Consolas",
        "image": "https://pt.static.webuy.com/images/category/playstation5-consolas.jpg",
        "hub_consola": False,
        "hub_acessorios": False,
        "hub_jogos": False,
    },
    "PS Vita Consolas": {
        "id": 506,
        "fatherId": 5,
        "title": "PS Vita Consolas",
        "url": "https://pt.webuy.com/search?categoryIds=991&categoryName=PS%20Vita%20Consolas",
        "image": "https://pt.static.webuy.com/images/category/ps-vita-consolas.jpg",
        "hub_consola": False,
        "hub_acessorios": False,
        "hub_jogos": False,
    },
    "PSP Consolas": {
        "id": 507,
        "fatherId": 5,
        "title": "PSP Consolas",
        "url": "https://pt.webuy.com/search?categoryIds=863&categoryName=PSP%20Consolas",
        "image": "https://pt.static.webuy.com/images/category/psp-consolas.jpg",
        "hub_consola": False,
        "hub_acessorios": False,
        "hub_jogos": False,
    },
    "Switch Consolas": {
        "id": 508,
        "fatherId": 5,
        "title": "Switch Consolas",
        "url": "https://pt.webuy.com/search?categoryIds=1048&categoryName=Switch%20Consolas",
        "image": "https://pt.static.webuy.com/images/category/switch-consolas.jpg",
        "hub_consola": False,
        "hub_acessorios": False,
        "hub_jogos": False,
    },
    "Wii Consolas": {
        "id": 509,
        "fatherId": 5,
        "title": "Wii Consolas",
        "url": "https://pt.webuy.com/search?categoryIds=1012&categoryName=Wii%20Consolas",
        "image": "https://pt.static.webuy.com/images/category/wii-consolas.jpg",
        "hub_consola": False,
        "hub_acessorios": False,
        "hub_jogos": False,
    },
    "Wii-U Consolas": {
        "id": 5010,
        "fatherId": 5,
        "title": "Wii-U Consolas",
        "url": "https://pt.webuy.com/search?categoryIds=1011&categoryName=Wii-U%20Consolas",
        "image": "https://pt.static.webuy.com/images/category/wii-u-consolas.jpg",
        "hub_consola": False,
        "hub_acessorios": False,
        "hub_jogos": False,
    },
    "Xbox 360 Consolas": {
        "id": 5011,
        "fatherId": 5,
        "title": "Xbox 360 Consolas",
        "url": "https://pt.webuy.com/search?categoryIds=1010&categoryName=Xbox%20360%20Consolas",
        "image": "https://pt.static.webuy.com/images/category/xbox-360-consolas.jpg",
        "hub_consola": False,
        "hub_acessorios": False,
        "hub_jogos": False,
    },
    "Xbox Consolas": {
        "id": 5012,
        "fatherId": 5,
        "title": "Xbox Consolas",
        "url": "https://pt.webuy.com/search?categoryIds=672&categoryName=Xbox%20Consolas",
        "image": "https://pt.static.webuy.com/images/category/xbox-consolas.jpg",
        "hub_consola": False,
        "hub_acessorios": False,
        "hub_jogos": False,
    },
    "Xbox One Consolas": {
        "id": 5013,
        "fatherId": 5,
        "title": "Xbox One Consolas",
        "url": "https://pt.webuy.com/search?categoryIds=1017&categoryName=Xbox%20One%20Consolas",
        "image": "https://pt.static.webuy.com/images/category/xbox-one-consolas.jpg",
        "hub_consola": False,
        "hub_acessorios": False,
        "hub_jogos": False,
    },
    "Xbox Series Consolas": {
        "id": 5014,
        "fatherId": 5,
        "title": "Xbox Series Consolas",
        "url": "https://pt.webuy.com/search?categoryIds=1091&categoryName=Xbox%20Series%20Consolas",
        "image": "https://pt.static.webuy.com/images/category/xbox-series-consolas.jpg",
        "hub_consola": False,
        "hub_acessorios": False,
        "hub_jogos": False,
    },
    "GBA Acessórios": {
        "id": 601,
        "fatherId": 6,
        "title": "GBA Acessórios",
        "url": "https://pt.webuy.com/search?categoryIds=1114&categoryName=GBA%20Acess%C3%B3rios",
        "image": "https://pt.static.webuy.com/images/category/gba-acess%C3%B3rios.jpg",
        "hub_consola": True,
        "hub_acessorios": True,
        "hub_jogos": False,
    },
    "GBA Consolas": {
        "id": 602,
        "fatherId": 6,
        "title": "GBA Consolas",
        "url": "https://pt.webuy.com/search?categoryIds=1115&categoryName=GBA%20Consolas",
        "image": "https://pt.static.webuy.com/images/category/gba-consolas.jpg",
        "hub_consola": False,
        "hub_acessorios": False,
        "hub_jogos": False,
    },
    "GBA Jogos": {
        "id": 603,
        "fatherId": 6,
        "title": "GBA Jogos",
        "url": "https://pt.webuy.com/search?categoryIds=1116&categoryName=GBA%20Jogos",
        "image": "https://pt.static.webuy.com/images/category/gba-jogos.jpg",
        "hub_consola": False,
        "hub_acessorios": False,
        "hub_jogos": True,
    },
    "Mega 32X Jogos": {
        "id": 604,
        "fatherId": 6,
        "title": "Mega 32X Jogos",
        "url": "https://pt.webuy.com/search?categoryIds=1062&categoryName=Mega%2032X%20Jogos",
        "image": "https://pt.static.webuy.com/images/category/mega-32x-jogos.jpg",
        "hub_consola": False,
        "hub_acessorios": False,
        "hub_jogos": True,
    },
    "Mega Drive Acessórios": {
        "id": 605,
        "fatherId": 6,
        "title": "Mega Drive Acessórios",
        "url": "https://pt.webuy.com/search?categoryIds=1063&categoryName=Mega%20Drive%20Acess%C3%B3rios",
        "image": "https://pt.static.webuy.com/images/category/mega-drive-acess%C3%B3rios.jpg",
        "hub_consola": True,
        "hub_acessorios": True,
        "hub_jogos": False,
    },
    "Mega Drive Consolas": {
        "id": 606,
        "fatherId": 6,
        "title": "Mega Drive Consolas",
        "url": "https://pt.webuy.com/search?categoryIds=1064&categoryName=Mega%20Drive%20Consolas",
        "image": "https://pt.static.webuy.com/images/category/mega-drive-consolas.jpg",
        "hub_consola": False,
        "hub_acessorios": False,
        "hub_jogos": False,
    },
    "Mega Drive Jogos": {
        "id": 607,
        "fatherId": 6,
        "title": "Mega Drive Jogos",
        "url": "https://pt.webuy.com/search?categoryIds=1065&categoryName=Mega%20Drive%20Jogos",
        "image": "https://pt.static.webuy.com/images/category/mega-drive-jogos.jpg",
        "hub_consola": False,
        "hub_acessorios": False,
        "hub_jogos": True,
    },
    "Mega-CD Jogos": {
        "id": 608,
        "fatherId": 6,
        "title": "Mega-CD Jogos",
        "url": "https://pt.webuy.com/search?categoryIds=1066&categoryName=Mega-CD%20Jogos",
        "image": "https://pt.static.webuy.com/images/category/mega-cd-jogos.jpg",
        "hub_consola": False,
        "hub_acessorios": False,
        "hub_jogos": True,
    },
    "PS1 Acessórios": {
        "id": 609,
        "fatherId": 6,
        "title": "PS1 Acessórios",
        "url": "https://pt.webuy.com/search?categoryIds=1098&categoryName=PS1%20Acess%C3%B3rios",
        "image": "https://pt.static.webuy.com/images/category/ps1-acess%C3%B3rios.jpg",
        "hub_consola": True,
        "hub_acessorios": True,
        "hub_jogos": False,
    },
    "PS1 Consolas": {
        "id": 6010,
        "fatherId": 6,
        "title": "PS1 Consolas",
        "url": "https://pt.webuy.com/search?categoryIds=1099&categoryName=PS1%20Consolas",
        "image": "https://pt.static.webuy.com/images/category/ps1-consolas.jpg",
        "hub_consola": False,
        "hub_acessorios": False,
        "hub_jogos": False,
    },
    "PS1 Jogos": {
        "id": 6011,
        "fatherId": 6,
        "title": "PS1 Jogos",
        "url": "https://pt.webuy.com/search?categoryIds=1100&categoryName=PS1%20Jogos",
        "image": "https://pt.static.webuy.com/images/category/ps1-jogos.jpg",
        "hub_consola": False,
        "hub_acessorios": False,
        "hub_jogos": True,
    },
    "PC Jogos": {
        "id": 701,
        "fatherId": 7,
        "title": "PC Jogos",
        "url": "https://pt.webuy.com/search?categoryIds=956&categoryName=PC%20Jogos",
        "image": "https://pt.static.webuy.com/images/category/pc-jogos.jpg",
        "hub_consola": False,
        "hub_acessorios": False,
        "hub_jogos": True,
    },
    "Playstation2 Jogos": {
        "id": 702,
        "fatherId": 7,
        "title": "Playstation2 Jogos",
        "url": "https://pt.webuy.com/search?categoryIds=403&categoryName=Playstation2%20Jogos",
        "image": "https://pt.static.webuy.com/images/category/playstation2-jogos.jpg",
        "hub_consola": False,
        "hub_acessorios": False,
        "hub_jogos": True,
    },
    "Playstation3 Jogos": {
        "id": 703,
        "fatherId": 7,
        "title": "Playstation3 Jogos",
        "url": "https://pt.webuy.com/search?categoryIds=808&categoryName=Playstation3%20Jogos",
        "image": "https://pt.static.webuy.com/images/category/playstation3-jogos.jpg",
        "hub_consola": False,
        "hub_acessorios": False,
        "hub_jogos": True,
    },
    "Playstation4 Jogos": {
        "id": 704,
        "fatherId": 7,
        "title": "Playstation4 Jogos",
        "url": "https://pt.webuy.com/search?categoryIds=1007&categoryName=Playstation4%20Jogos",
        "image": "https://pt.static.webuy.com/images/category/playstation4-jogos.jpg",
        "hub_consola": False,
        "hub_acessorios": False,
        "hub_jogos": True,
    },
    "Playstation5 Jogos": {
        "id": 705,
        "fatherId": 7,
        "title": "Playstation5 Jogos",
        "url": "https://pt.webuy.com/search?categoryIds=1089&categoryName=Playstation5%20Jogos",
        "image": "https://pt.static.webuy.com/images/category/playstation5-jogos.jpg",
        "hub_consola": False,
        "hub_acessorios": False,
        "hub_jogos": True,
    },
    "PS Vita Jogos": {
        "id": 706,
        "fatherId": 7,
        "title": "PS Vita Jogos",
        "url": "https://pt.webuy.com/search?categoryIds=1005&categoryName=PS%20Vita%20Jogos",
        "image": "https://pt.static.webuy.com/images/category/ps-vita-jogos.jpg",
        "hub_consola": False,
        "hub_acessorios": False,
        "hub_jogos": True,
    },
    "PSP Jogos": {
        "id": 707,
        "fatherId": 7,
        "title": "PSP Jogos",
        "url": "https://pt.webuy.com/search?categoryIds=767&categoryName=PSP%20Jogos",
        "image": "https://pt.static.webuy.com/images/category/psp-jogos.jpg",
        "hub_consola": False,
        "hub_acessorios": False,
        "hub_jogos": True,
    },
    "Switch Jogos": {
        "id": 708,
        "fatherId": 7,
        "title": "Switch Jogos",
        "url": "https://pt.webuy.com/search?categoryIds=1049&categoryName=Switch%20Jogos",
        "image": "https://pt.static.webuy.com/images/category/switch-jogos.jpg",
        "hub_consola": False,
        "hub_acessorios": False,
        "hub_jogos": True,
    },
    "Wii Jogos": {
        "id": 709,
        "fatherId": 7,
        "title": "Wii Jogos",
        "url": "https://pt.webuy.com/search?categoryIds=795&categoryName=Wii%20Jogos",
        "image": "https://pt.static.webuy.com/images/category/wii-jogos.jpg",
        "hub_consola": False,
        "hub_acessorios": False,
        "hub_jogos": True,
    },
    "Wii-U Jogos": {
        "id": 7010,
        "fatherId": 7,
        "title": "Wii-U Jogos",
        "url": "https://pt.webuy.com/search?categoryIds=993&categoryName=Wii-U%20Jogos",
        "image": "https://pt.static.webuy.com/images/category/wii-u-jogos.jpg",
        "hub_consola": False,
        "hub_acessorios": False,
        "hub_jogos": True,
    },
    "Xbox 360 Jogos": {
        "id": 7011,
        "fatherId": 7,
        "title": "Xbox 360 Jogos",
        "url": "https://pt.webuy.com/search?categoryIds=1004&categoryName=Xbox%20360%20Jogos",
        "image": "https://pt.static.webuy.com/images/category/xbox-360-jogos.jpg",
        "hub_consola": False,
        "hub_acessorios": False,
        "hub_jogos": True,
    },
    "Xbox Jogos": {
        "id": 7012,
        "fatherId": 7,
        "title": "Xbox Jogos",
        "url": "https://pt.webuy.com/search?categoryIds=673&categoryName=Xbox%20Jogos",
        "image": "https://pt.static.webuy.com/images/category/xbox-jogos.jpg",
        "hub_consola": False,
        "hub_acessorios": False,
        "hub_jogos": True,
    },
    "Xbox One Jogos": {
        "id": 7013,
        "fatherId": 7,
        "title": "Xbox One Jogos",
        "url": "https://pt.webuy.com/search?categoryIds=1006&categoryName=Xbox%20One%20Jogos",
        "image": "https://pt.static.webuy.com/images/category/xbox-one-jogos.jpg",
        "hub_consola": False,
        "hub_acessorios": False,
        "hub_jogos": True,
    },
    "Xbox Series Jogos": {
        "id": 7014,
        "fatherId": 7,
        "title": "Xbox Series Jogos",
        "url": "https://pt.webuy.com/search?categoryIds=1093&categoryName=Xbox%20Series%20Jogos",
        "image": "https://pt.static.webuy.com/images/category/xbox-series-jogos.jpg",
        "hub_consola": False,
        "hub_acessorios": False,
        "hub_jogos": True,
    },
    "Xbox Smart Delivery Jogos": {
        "id": 7015,
        "fatherId": 7,
        "title": "Xbox Smart Delivery Jogos",
        "url": "https://pt.webuy.com/search?categoryIds=1092&categoryName=Xbox%20Smart%20Delivery%20Jogos",
        "image": "https://pt.static.webuy.com/images/category/xbox-smart-delivery-jogos.jpg",
        "hub_consola": False,
        "hub_acessorios": False,
        "hub_jogos": True,
    },
    "PSP UMD Filmes": {
        "id": 1401,
        "fatherId": 14,
        "title": "PSP UMD Filmes",
        "url": "https://pt.webuy.com/search?categoryIds=776&categoryName=PSP%20UMD%20Filmes",
        "image": "https://pt.static.webuy.com/images/category/psp-umd-filmes.jpg",
        "hub_consola": True,
        "hub_acessorios": False,
        "hub_jogos": False,
    },
}
