{
    "3DS": {
        "id": 1,
        "title": "3DS",
        "url": "https://pt.webuy.com/search?productLineId=79&productLineName=3DS",
        "image": "https://pt.static.webuy.com/images/supercat/1/product-lines/3ds.jpg",
        "hub_consola": True,
        "hub_acessorios": False,
        "hub_jogos": False,
    },
    "DS": {
        "id": 2,
        "title": "DS",
        "url": "https://pt.webuy.com/search?productLineId=67&productLineName=DS",
        "image": "https://pt.static.webuy.com/images/supercat/1/product-lines/ds.jpg",
        "hub_consola": True,
        "hub_acessorios": False,
        "hub_jogos": False,
    },
    "GameCube": {
        "id": 3,
        "title": "GameCube",
        "url": "https://pt.webuy.com/search?productLineId=75&productLineName=GameCube",
        "image": "https://pt.static.webuy.com/images/supercat/1/product-lines/gamecube.jpg",
        "hub_consola": True,
        "hub_acessorios": False,
        "hub_jogos": False,
    },
    "Jogos Acessórios": {
        "id": 4,
        "title": "Jogos Acessórios",
        "url": "https://pt.webuy.com/search?productLineId=53&productLineName=Jogos%20Acess%C3%B3rios",
        "image": "https://pt.static.webuy.com/images/supercat/1/product-lines/jogos-acess%C3%B3rios.jpg",
        "hub_consola": False,
        "hub_acessorios": True,
        "hub_jogos": False,
    },
    "Jogos Consolas": {
        "id": 5,
        "title": "Jogos Consolas",
        "url": "https://pt.webuy.com/search?productLineId=52&productLineName=Jogos%20Consolas",
        "image": "https://pt.static.webuy.com/images/supercat/1/product-lines/jogos-consolas.jpg",
        "hub_consola": False,
        "hub_acessorios": False,
        "hub_jogos": False,
    },
    "Jogos Retro": {
        "id": 6,
        "title": "Jogos Retro",
        "url": "https://pt.webuy.com/search?productLineId=94&productLineName=Jogos%20Retro",
        "image": "https://pt.static.webuy.com/images/supercat/1/product-lines/jogos-retro.jpg",
        "hub_consola": False,
        "hub_acessorios": False,
        "hub_jogos": True,
    },
    "Jogos Software": {
        "id": 7,
        "title": "Jogos Software",
        "url": "https://pt.webuy.com/search?productLineId=51&productLineName=Jogos%20Software",
        "image": "https://pt.static.webuy.com/images/supercat/1/product-lines/jogos-software.jpg",
        "hub_consola": False,
        "hub_acessorios": False,
        "hub_jogos": True,
    },
    "PC Jogos": {
        "id": 8,
        "title": "PC Jogos",
        "url": "https://pt.webuy.com/search?productLineId=73&productLineName=PC%20Jogos",
        "image": "https://pt.static.webuy.com/images/supercat/1/product-lines/pc-jogos.jpg",
        "hub_consola": False,
        "hub_acessorios": False,
        "hub_jogos": True,
    },
    "PlayStation2": {
        "id": 9,
        "title": "PlayStation2",
        "url": "https://pt.webuy.com/search?productLineId=69&productLineName=PlayStation2",
        "image": "https://pt.static.webuy.com/images/supercat/1/product-lines/playstation2.jpg",
        "hub_consola": True,
        "hub_acessorios": False,
        "hub_jogos": False,
    },
    "PlayStation3": {
        "id": 10,
        "title": "PlayStation3",
        "url": "https://pt.webuy.com/search?productLineId=70&productLineName=PlayStation3",
        "image": "https://pt.static.webuy.com/images/supercat/1/product-lines/playstation3.jpg",
        "hub_consola": True,
        "hub_acessorios": False,
        "hub_jogos": False,
    },
    "PlayStation4": {
        "id": 11,
        "title": "PlayStation4",
        "url": "https://pt.webuy.com/search?productLineId=82&productLineName=PlayStation4",
        "image": "https://pt.static.webuy.com/images/supercat/1/product-lines/playstation4.jpg",
        "hub_consola": True,
        "hub_acessorios": False,
        "hub_jogos": False,
    },
    "PlayStation5": {
        "id": 12,
        "title": "PlayStation5",
        "url": "https://pt.webuy.com/search?productLineId=97&productLineName=PlayStation5",
        "image": "https://pt.static.webuy.com/images/supercat/1/product-lines/playstation5.jpg",
        "hub_consola": True,
        "hub_acessorios": False,
        "hub_jogos": False,
    },
    "PS Vita": {
        "id": 13,
        "title": "PS Vita",
        "url": "https://pt.webuy.com/search?productLineId=81&productLineName=PS%20Vita",
        "image": "https://pt.static.webuy.com/images/supercat/1/product-lines/ps-vita.jpg",
        "hub_consola": True,
        "hub_acessorios": False,
        "hub_jogos": False,
    },
    "PSP": {
        "id": 14,
        "title": "PSP",
        "url": "https://pt.webuy.com/search?productLineId=74&productLineName=PSP",
        "image": "https://pt.static.webuy.com/images/supercat/1/product-lines/psp.jpg",
        "hub_consola": True,
        "hub_acessorios": False,
        "hub_jogos": False,
    },
    "Switch": {
        "id": 15,
        "title": "Switch",
        "url": "https://pt.webuy.com/search?productLineId=90&productLineName=Switch",
        "image": "https://pt.static.webuy.com/images/supercat/1/product-lines/switch.jpg",
        "hub_consola": True,
        "hub_acessorios": False,
        "hub_jogos": False,
    },
    "Wii": {
        "id": 16,
        "title": "Wii",
        "url": "https://pt.webuy.com/search?productLineId=68&productLineName=Wii",
        "image": "https://pt.static.webuy.com/images/supercat/1/product-lines/wii.jpg",
        "hub_consola": True,
        "hub_acessorios": False,
        "hub_jogos": False,
    },
    "Wii-U": {
        "id": 17,
        "title": "Wii-U",
        "url": "https://pt.webuy.com/search?productLineId=86&productLineName=Wii-U",
        "image": "https://pt.static.webuy.com/images/supercat/1/product-lines/wii-u.jpg",
        "hub_consola": True,
        "hub_acessorios": False,
        "hub_jogos": False,
    },
    "Xbox": {
        "id": 18,
        "title": "Xbox",
        "url": "https://pt.webuy.com/search?productLineId=71&productLineName=Xbox",
        "image": "https://pt.static.webuy.com/images/supercat/1/product-lines/xbox.jpg",
        "hub_consola": True,
        "hub_acessorios": False,
        "hub_jogos": False,
    },
    "Xbox 360": {
        "id": 19,
        "title": "Xbox 360",
        "url": "https://pt.webuy.com/search?productLineId=72&productLineName=Xbox%20360",
        "image": "https://pt.static.webuy.com/images/supercat/1/product-lines/xbox-360.jpg",
        "hub_consola": True,
        "hub_acessorios": False,
        "hub_jogos": False,
    },
    "Xbox One": {
        "id": 20,
        "title": "Xbox One",
        "url": "https://pt.webuy.com/search?productLineId=83&productLineName=Xbox%20One",
        "image": "https://pt.static.webuy.com/images/supercat/1/product-lines/xbox-one.jpg",
        "hub_consola": True,
        "hub_acessorios": False,
        "hub_jogos": False,
    },
    "Xbox Series": {
        "id": 21,
        "title": "Xbox Series",
        "url": "https://pt.webuy.com/search?productLineId=98&productLineName=Xbox%20Series",
        "image": "https://pt.static.webuy.com/images/supercat/1/product-lines/xbox-series.jpg",
        "hub_consola": True,
        "hub_acessorios": False,
        "hub_jogos": False,
    },
}
